- .gitignore
- lib/application.ts
- lib/services/item_manager.ts
- lib/services/protocol_service.ts
- lib/utils.ts
- test/auth.test.js
- test/keys.test.js
- test/protocol.test.js
- test/sync_tests/online.test.js
- test/upgrading.test.js
- test/utils.test.js
- webpack.dev.js
Compare against an up to date itemsKeys value after running operations in the itemManager
> fix: itemsKeys bug

- lib/models/core/item.ts
- lib/protocol/payloads/deltas/remote_conflicts.ts
- test/model_tests/importing.test.js
Lets a user to restore their previously-deleted notes from a backup
> Allow reimporting deleted notes

- test/auth.test.js
- test/lib/factory.js
Forgot to push my test for this one
> test upgrading without an account and a passcode

- dist/@types/services/pure_service.d.ts
- dist/@types/services/storage_service.d.ts
- lib/services/pure_service.ts
- lib/services/storage_service.ts
We need this to let the user clear their storage when they can't remember their passcode
> fix: allow clearing storage when app is locked

- lib/services/history/history_manager.ts
The web app depends on this type
> fix: export RemoteHistoryListEntry

- dist/@types/models/app/extension.d.ts
- dist/snjs.js
- lib/models/app/extension.ts
- lib/services/actions_service.ts
No need to persist extension visibility.
> fix: extension visibility should not be persisted

- dist/@types/index.d.ts
- dist/@types/models/app/userPrefs.d.ts
- dist/@types/models/index.d.ts
- dist/snjs.js
- lib/index.ts
- lib/models/app/userPrefs.ts
- lib/models/index.ts
This brings mobile-specific preferences to snjs. I wonder if pref keys should be different from the web.
> feature: mobile user preferences

- dist/@types/application.d.ts
- dist/@types/services/alert_service.d.ts
- dist/@types/services/api/messages.d.ts
- dist/snjs.js
Forgot to run this after the last PR
> chore: bundle & export types

- dist/@types/index.d.ts
- dist/@types/protocol/intents.d.ts
- dist/@types/services/api/api_service.d.ts
- dist/@types/services/api/responses.d.ts
- dist/@types/services/history/history_manager.d.ts
- dist/@types/utils.d.ts
- dist/snjs.js
- lib/index.ts
- lib/protocol/intents.ts
- lib/protocol/operator/004/operator_004.ts
- lib/services/api/api_service.ts
- lib/services/api/responses.ts
- lib/services/history/history_manager.ts
- lib/utils.ts
- test/004.test.js
- test/history.test.js
- test/utils.test.js
- Fixes issue where revisions of an item that is created from a duplication event couldn't be decrypted
> fix: duplicate revision decryption

- dist/@types/index.d.ts
- dist/@types/models/app/userPrefs.d.ts
- dist/@types/models/index.d.ts
- dist/snjs.js
- lib/index.ts
- lib/models/app/userPrefs.ts
- lib/models/index.ts
Mobile uses local preferences from now on.
> refactor: remove Mobile user preferences

- dist/@types/application.d.ts
- dist/snjs.js
- lib/application.ts
Required for https://github.com/standardnotes/decrypt/pull/2
> feature: let apps set persistence policy to ephemeral

- lib/application.ts
- lib/protocol/operator/operator.ts
- lib/protocol/root_key.ts
- lib/services/protocol_service.ts
- package-lock.json
- package.json
Replacing `sncrypto` with our new `@standardnotes/sncrypto-common` package
> feat: replace sncrypto with @standardnotes/sncrypto-common package

- lib/index.ts
- lib/models/index.ts
- lib/protocol/index.ts
- lib/protocol/payloads/index.ts
- lib/services/index.ts
- package.json
Add missing exports that are used by `web` application
> fix: add missing exports

- lib/application.ts
- lib/log.ts
- lib/models/app/tag.ts
- lib/protocol/collection/item_collection.ts
- lib/protocol/payloads/deltas/conflict.ts
- lib/services/item_manager.ts
- lib/services/sync/sync_op_status.ts
- lib/services/sync/sync_service.ts
- package-lock.json
- package.json
- test/model_tests/notes_tags.test.js
Sort collection items according to the user's locale. This fixes an issue where tags starting with the same letter but different casing would not be correctly sorted.
> Sort using localeCompare

- lib/application.ts
- lib/events.ts
- lib/index.ts
- lib/models/app/userPrefs.ts
- lib/models/core/item.ts
- lib/models/index.ts
- lib/services/item_manager.ts
- lib/services/preferences_service.ts
- lib/services/singleton_manager.ts
- lib/services/sync/sync_service.ts
- package.json
- test/app-group.test.js
- test/application.test.js
- test/auth.test.js
- test/backups.test.js
- test/lib/factory.js
- test/model_tests/appmodels.test.js
- test/model_tests/importing.test.js
- test/model_tests/items.test.js
- test/model_tests/mapping.test.js
- test/model_tests/notes_tags.test.js
- test/preferences.test.js
- test/session.test.js
- test/singletons.test.js
- test/storage.test.js
- test/sync_tests/discordance.test.js
- test/sync_tests/duplication.test.js
- test/sync_tests/offline.test.js
- test/sync_tests/online.test.js
- test/test.html
Extracts web preferences to SNJS as a generalized synced preferences mechanism.
Public API is `SNApplication.getPreference()/setPreference()`.
> feat: synced preferences

- package.json
- test.sh
- test/model_tests/performance.test.js
- test/session.test.js
- test/test.html
Increased from 10 minutes to 20 minutes
> fix: test suite timeouts

- lib/application.ts
- lib/services/api/messages.ts
- package.json
(Nevermind the branch name, I got my features mixed up)
> fix: present confirm dialog before revoking session

- package.json
- packages/snjs/.eslintrc
- packages/snjs/lib/application.ts
- packages/snjs/lib/challenges.ts
- packages/snjs/lib/services/api/messages.ts
- packages/snjs/package.json
- test/lib/factory.js
- test/model_tests/importing.test.js
- test/protection.test.js
- test/test.html
This used to be in web but it fits better in SNJS now that we can get arbitrary user input from it with challenges.
> feat: handle password retrieval for decrypting import files

- packages/config/package.json
- packages/config/src/.prettierrc
I think this matches `.eslintrc`: https://github.com/standardnotes/snjs/blob/da023dd2d3568b972c5eed259067375bb0505669/packages/config/src/.eslintrc#L20
> feat: add .prettierrc to config package

- packages/snjs/lib/application.ts
- packages/snjs/lib/services/protection_service.ts
- packages/snjs/package.json
- test/protection.test.js
With this PR we'll end up with:
- `SNApplication.hasProtections()`: to determine if a user can use the feature at all (which they can't if they don't have an account, passcode, or biometrics authentication)
- `SNApplication.areProtectionsEnabled()`: to determine if protections are enabled/disabled
> protections public methods

- packages/snjs/lib/application.ts
- packages/snjs/lib/services/protection_service.ts
- packages/snjs/package.json
Add getLaunchChallenge method that can be overriden by clients.
> feat: add getLaunchChallenge method

- packages/snjs/lib/services/api/messages.ts
- packages/snjs/lib/services/api/session_manager.ts
- packages/snjs/package.json
Return prompt title for custom 2FA challenge.
> Add title for 2FA challenge

- packages/auth/package.json
- packages/auth/src/Domain/Token/Token.ts
- packages/auth/src/Domain/User/AuthMethods.ts
- packages/auth/src/Domain/Uuid/Uuid.ts
[Related task](https://app.asana.com/0/1185703377033953/1200207978162343/f)
> feat: added AuthMethods and extracted Uuid to auth SDK

- .github/codeql/codeql-config.yml
- .github/codeql/custom-queries/javascript/qlpack.yml
- .github/workflows/codeql-analysis.yml
- .gitignore
- .prettierignore
Adds code analysis via CodeQL. The following queries are used:
- `security-and-quality`: queries from security-extended, plus maintainability and reliability queries
- custom queries located in [.github/codeql/custom-queries/javascript](https://github.com/standardnotes/snjs/tree/codeql-analysis/.github/codeql/custom-queries/javascript).
See the [code scanning alerts generated by this PR](https://github.com/standardnotes/mobile/security/code-scanning?query=ref%3Arefs%2Fpull%2F414%2Fmerge).
> chore: codeql analysis action

- packages/snjs/lib/index.ts
- packages/snjs/lib/protocol/collection/payload_collection.ts
- packages/snjs/lib/protocol/payloads/deltas/remote_conflicts.ts
- packages/snjs/lib/protocol/payloads/functions.ts
- packages/snjs/lib/utils.ts
- packages/snjs/package.json
- test/lib/factory.js
- test/sync_tests/conflicting.test.js
- test/utils.test.js
Fixes issue where importing a backup belonging to another account would sometimes create duplicates or tags resulting in less associations than expected.
> UUID conflict fix

- packages/snjs/package.json
Forgot to increment version on https://github.com/standardnotes/snjs/pull/291
> release: 2.2.1

- packages/snjs/lib/application.ts
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/api/session_manager.ts
- packages/snjs/lib/services/history/history_manager.ts
- packages/snjs/lib/services/key_recovery_service.ts
- packages/snjs/package.json
- feat: migrate deleteSession to api/v1
- chore(version): 2.7.9
> feat: migrate deleteSession to api/v1

- packages/snjs/package.json
(forgot to increment version on https://github.com/standardnotes/snjs/pull/342)
> chore: increment version

- docker-compose.yml
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/api/http_service.ts
- packages/snjs/lib/services/api/responses.ts
- packages/snjs/lib/services/api/session.ts
- packages/snjs/lib/services/api/session_manager.ts
- packages/snjs/package.json
- test/session.test.js
- feat: migrate refreshSession to api/v1
- chore(version): 2.7.10
> feat: migrate refreshSession to api/v1

- docker-compose.yml
- packages/settings/package.json
- packages/settings/src/Domain/Setting/SettingPayload.ts
- packages/settings/src/Domain/index.ts
- packages/snjs/lib/application.ts
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/api/messages.ts
- packages/snjs/lib/services/api/responses.ts
- packages/snjs/lib/services/settings_service/SNSettingsService.ts
- packages/snjs/lib/services/settings_service/SettingsGateway.ts
- packages/snjs/lib/services/settings_service/SettingsProvider.ts
- packages/snjs/lib/services/settings_service/index.ts
- packages/snjs/package.json
- packages/snjs/test/lib/settings.test.js
- packages/snjs/test/lib/settings.test.ts
- yarn.lock
- Implement SNSettingsService for reading, updating, deleting and listing settings
- Implement test for SNSettingsService
> feat: settings service 

- package.json
- packages/snjs/lib/application.ts
- packages/snjs/lib/services/features_service.spec.ts
- packages/snjs/lib/services/features_service.ts
- packages/snjs/lib/storage_keys.ts
- packages/snjs/package.json
- packages/snjs/test/lib/features.test.ts
Store user features fetched from /features endpoint.
> feat: store user features

- packages/snjs/jest.e2e.config.ts
- packages/snjs/jest.unit.config.ts
- only `tests names` and `coverage information` are shown within test output
Asana task: https://app.asana.com/0/1199914526147392/1200868522372682
> fix: cleanup test output

- docker-compose.yml
- packages/snjs/lib/application.ts
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/api/messages.ts
- packages/snjs/lib/services/api/responses.ts
- packages/snjs/lib/services/api/session_manager.ts
- packages/snjs/lib/services/credential_service.ts
- packages/snjs/package.json
- packages/snjs/test/lib/keys.test.js
- packages/snjs/test/lib/session.test.js
- packages/snjs/test/lib/upgrading.test.js
- yarn.lock
Internal link: https://app.asana.com/0/1199914526147392/1200887853314814/f
> feat: add email changing

- packages/snjs/lib/application.ts
- packages/snjs/lib/services/api/session_manager.ts
- packages/snjs/mocha/session.test.js
- packages/snjs/package.json
Implement revoking other sessions in SessionManager.
Implement e2e test.
> feat: enable revoking other sessions

- packages/snjs/lib/services/api/websockets_service.ts
- packages/snjs/package.json
https://app.asana.com/0/1185703377033953/1200933763648201/f
> fix: catch websocket connection error

- .github/workflows/nightly.yml
Adding nightly builds that will run at 2:15 AM UTC every day. 
Just in case we have some flaky tests that could be picked up.
> feat: add nightly builds

- packages/domain-events/package.json
- packages/domain-events/src/Domain/Event/SubscriptionCancelledEventPayload.ts
- packages/domain-events/src/Domain/Event/SubscriptionExpiredEventPayload.ts
- packages/domain-events/src/Domain/Event/SubscriptionPurchasedEventPayload.ts
- packages/domain-events/src/Domain/Event/SubscriptionRefundedEventPayload.ts
- packages/domain-events/src/Domain/Event/SubscriptionRenewedEventPayload.ts
Internal link: https://app.asana.com/0/1199914526147392/1201153040219257/f
> feat: add offline option for subscription events

- packages/snjs/lib/protocol/collection/collection.ts
- packages/snjs/lib/protocol/collection/notes_display_criteria.ts
- packages/snjs/mocha/collections.test.js
- packages/snjs/mocha/lib/factory.js
- packages/snjs/mocha/model_tests/notes_tags.test.js
- packages/snjs/mocha/payload_encryption.test.js
(Asana task: https://app.asana.com/0/1199914526147392/1201177736494461)
> feat: include notes that have tag titles that match search query

- packages/snjs/lib/application.ts
- packages/snjs/lib/constants.ts
- packages/snjs/lib/models/app/feature_repo.ts
- packages/snjs/lib/models/generator.ts
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/features_service.spec.ts
- packages/snjs/lib/services/features_service.ts
- packages/snjs/lib/services/item_manager.ts
- packages/snjs/lib/services/migration_service.ts
- packages/snjs/lib/storage_keys.ts
- packages/snjs/mocha/features.test.js
- packages/snjs/mocha/storage.test.js
- packages/snjs/package.json
https://app.asana.com/0/1200980603427038/1201359252801171
> fix: move offline features to be item based

- packages/common/package.json
- packages/common/src/Domain/Content/ContentType.ts
- packages/snjs/lib/application.ts
- packages/snjs/lib/index.ts
- packages/snjs/lib/migrations/2_20_0.ts
- packages/snjs/lib/migrations/index.ts
- packages/snjs/lib/models/content_types.ts
- packages/snjs/lib/services/component_manager.ts
- packages/snjs/lib/services/item_manager.ts
- packages/snjs/lib/services/sync/filter.ts
- packages/snjs/mocha/migrations/migration.test.js
- packages/snjs/mocha/protocol.test.js
- packages/snjs/mocha/sync_tests/online.test.js
- packages/snjs/mocha/test.html
- packages/snjs/package.json
Internal link: https://app.asana.com/0/1160985268757888/1201476283236493/f
> feat: remove legacy mfa

- packages/snjs/lib/application.ts
- packages/snjs/lib/models/functions.ts
- packages/snjs/lib/services/item_manager.spec.ts
- packages/snjs/lib/services/item_manager.ts
- packages/snjs/mocha/item_manager.test.js
- packages/snjs/mocha/lib/factory.js
- packages/snjs/mocha/model_tests/notes_tags_folders.test.js
- packages/snjs/package.json
> feat: add addTagHierarchyToNote & isTemplateItem

- packages/features/package.json
- packages/features/src/Domain/Feature/features.json
- packages/snjs/package.json
> chore: update token-vault and bold-editor

- .github/pull_request_template.md
What kind of change does this PR introduce?
Add a Github Pull Request Template for better documenting our changes
N/A
> feat: add github pull request template

- packages/auth/package.json
- packages/common/package.json
- packages/domain-events-infra/package.json
- packages/domain-events/package.json
- packages/features/package.json
- packages/settings/package.json
- packages/snjs/package.json
- packages/time/package.json
- yarn.lock
What kind of change does this PR introduce?
When we are not locked on specific versions, trying to switch to lerna versioning will always trigger a cascade of package changes for every package.
Internal link: https://app.asana.com/0/1201371033937453/1201539608517479/f
> fix: versioning and package dependencies

- packages/settings/src/Domain/EmailBackup/EmailBackupFrequency.ts
- packages/snjs/lib/application.ts
- packages/snjs/lib/services/settings_service/SNSettingsService.ts
- packages/snjs/package.json
- yarn.lock
Internal link: https://app.asana.com/0/1201371033937453/1201518622825710
> feat: add "Disabled" option to email backup frequency

- packages/time/src/Domain/Time/Timer.spec.ts
- packages/time/src/Domain/Time/Timer.ts
- packages/time/src/Domain/Time/TimerInterface.ts
Add converting date to milliseconds on Timer.
Internal link: -
> feat: add converting date to milliseconds

- packages/time/src/Domain/Time/Timer.spec.ts
- packages/time/src/Domain/Time/Timer.ts
- packages/time/src/Domain/Time/TimerInterface.ts
> feat: add converting date to microseconds

- packages/domain-events-infra/package.json
- packages/domain-events/package.json
- yarn.lock
Fix package dependencies in `domain-events` and `domain-events-infra`
N/A
> fix: auth and domain-events dependencies

- packages/settings/src/Domain/DropboxBackupFrequency/DropboxBackupFrequency.ts
- packages/settings/src/Domain/Setting/SettingName.ts
- packages/settings/src/Domain/index.ts
Add Dropbox backup frequency setting
> feat: add dropbox backup frequency setting

- .github/pull_request_template.md
Fix PR template to latest established
N/A
> fix: pr template

- packages/settings/src/Domain/OneDriveBackupFrequency/OneDriveBackupFrequency.ts
- packages/settings/src/Domain/Setting/SettingName.ts
One drive backup frequency setting
> feat: add one drive backup frequency setting

- packages/settings/src/Domain/Setting/SettingName.ts
Add cloud backup settings names for backup url storing
N/A
> feat: add cloud backup settings names

- packages/snjs/lib/application.ts
- packages/snjs/lib/models/app/smartTag.ts
- packages/snjs/lib/models/core/predicate.ts
- packages/snjs/lib/models/mutator.ts
- packages/snjs/lib/services/item_manager.spec.ts
- packages/snjs/lib/services/item_manager.ts
- packages/snjs/mocha/lib/factory.js
- packages/snjs/mocha/model_tests/notes_smart_tags.test.js
- packages/snjs/mocha/session.test.js
- packages/snjs/mocha/test.html
Add smart tags support in SNJS
https://app.asana.com/0/1201409453293587/1201505386094904
> feat: smart tags native support

- .github/workflows/git-sync.yml
- .github/workflows/publish-beta.yml
- .github/workflows/publish.yml
Git sync should be run:
- asynchronously on any given branch except `master` and `beta/*` branches.
- synchronously (after publishing and versioning of packages) on `master` and `beta/*` branches.
https://app.asana.com/0/1200980603427038/1201564753368422/f
> fix: git sync race conditions

- .husky/pre-commit
- linter.tsconfig.json
- package.json
- yarn.lock
Add global linter config so VSCode properly interprets subpackages. Added Husky pre-commit hooks to check linter
https://app.asana.com/0/1160985268757888/1201608308325712/f
> feat: add global linter config for VSCode

- packages/snjs/lib/models/app/userPrefs.ts
Adds a `NotesHideEditorIcon` PrefKey
> feat: Add NotesHideEditorIcon pref key

- packages/snjs/mocha/settings.test.js
Fix failing tests on Canary builds
https://app.asana.com/0/0/1201645891969016/f
> fix: updating fake settings tests

- packages/auth/package.json
- packages/auth/src/Domain/Decoder/TokenDecoder.spec.ts
- packages/auth/src/Domain/Decoder/TokenDecoder.ts
- packages/auth/src/Domain/Decoder/TokenDecoderInterface.ts
- packages/auth/src/Domain/index.ts
- yarn.lock
Add token decoder. It is extracted from Auth project and will soon include the valet token handling from Files project
https://app.asana.com/0/1199942776723820/1201636055949681/f
> feat: add token decoder

- .github/workflows/publish.yml
- checks if new changes on `packages/decrypt/dist` and commits them before bumping versions
[Internal link](https://app.asana.com/0/1160985268757888/1198887823085525)
> fix: commit @standardnotes/decrypt built files

- packages/snjs/lib/models/app/tag.ts
- packages/snjs/lib/protocol/payloads/functions.ts
- packages/snjs/lib/protocol/payloads/generator.ts
- packages/snjs/lib/protocol/payloads/pure_payload.ts
- packages/snjs/lib/services/item_manager.ts
- packages/snjs/lib/utils.ts
Rethink parent tag relationship to make it more explicit.
https://app.asana.com/0/0/1201647349940603/f
> fix: refactor tag parent reference

- packages/features/src/Domain/Feature/FeatureDescription.ts
- packages/features/src/Domain/Feature/Features.ts
Adds names to some unnamed features to show in welcome email
> feat: add names to some unnamed features

- packages/domain-events/package.json
- packages/domain-events/src/Domain/Event/ExtensionKeyGrantedEventPayload.ts
Adds a `subscriptionFeatures` field to `ExtensionKeyGrantedEventPayload` for new subscription email.
> feat: add features list to extension key granted event

- packages/snjs/lib/types.ts
[Internal link](https://app.asana.com/0/1200588672119490/1201709907433958)
> feat: add new icon types

- packages/snjs/lib/index.ts
- packages/snjs/lib/services/index.ts
> fix: export ActionVerb from lib index instead of services

- packages/filepicker/example/src/index.ts
- packages/snjs/lib/application.ts
- packages/snjs/lib/options.ts
- packages/snjs/lib/services/files/file_service.spec.ts
- packages/snjs/lib/services/files/file_service.ts
- packages/snjs/lib/services/sync/sync_service.ts
- packages/snjs/mocha/lib/factory.js
> refactor: application constructor

- docker-compose.yml
- packages/snjs/lib/services/api/api_service.ts
- packages/snjs/lib/services/api/http_service.ts
Fix uploading file chunks by raw bytes in the request payload instead of JSON payload.
[Internal link](https://app.asana.com/0/1199942776723820/1201880983654581/f)
> fix: uploading file chunks as raw bytes in request

- packages/snjs/lib/application.ts
- packages/snjs/lib/index.ts
- packages/snjs/lib/services/Sync/SyncService.ts
- packages/snjs/lib/services/Sync/Types.ts
- packages/snjs/lib/services/Sync/index.ts
- packages/snjs/lib/services/index.ts
- packages/snjs/mocha/model_tests/importing.test.js
- packages/snjs/mocha/sync_tests/online.test.js
> refactor: refactor sync method into smaller parts

- packages/payloads/src/Domain/Predicate/Generators.ts
- packages/payloads/src/Domain/Predicate/Interface.ts
- packages/payloads/src/Domain/Predicate/Predicate.spec.ts
- packages/snjs/lib/models/app/SmartView.ts
> fix: includes predicate

- packages/snjs/lib/services/Features/ClientInterface.ts
[Internal link](https://app.asana.com/0/1201611182420182/1201836690484207)
> fix: add isExperimentalFeature to ClientInterface

- packages/features/src/Domain/Feature/FeatureIdentifier.ts
[Internal link](https://app.asana.com/0/1201611182420182/1201836690484207)
> fix: remove AccountSwitcher from experimental features list

- packages/components/all/checksums.json
- packages/components/all/org.standardnotes.theme-dynamic/dist/dist.css
- packages/components/all/org.standardnotes.theme-dynamic/dist/dist.css.map
- packages/components/all/org.standardnotes.theme-dynamic/package.json
- packages/components/package.json
- packages/features/src/Domain/Feature/Features.ts
- yarn.lock
[Internal link](https://app.asana.com/0/1201781071449998/1201936716184193)
> chore(deps): update dynamic-theme

- packages/filepicker/src/utils.spec.ts
- packages/filepicker/src/utils.ts
> feat: add formatSizeToReadableString function

- docker-compose.yml
- packages/snjs/mocha/files.test.js
Fix consecutive uploads on file system.
[Internal link](https://app.asana.com/0/1199942776723820/1201946200116907/f)
> fix: consecutive uploads

- packages/filepicker/example/src/classic_file_api.ts
- packages/filepicker/example/src/file_system_api.ts
- packages/filepicker/src/Classic/ClassicReader.ts
- packages/filepicker/src/Streaming/StreamingReader.ts
- packages/filepicker/src/types.ts
- packages/snjs/lib/models/app/file.ts
- packages/snjs/lib/services/Files/FileService.ts
- packages/snjs/lib/services/Items/ClientInterface.ts
- packages/snjs/lib/services/Items/ItemManager.spec.ts
- packages/snjs/lib/services/Items/ItemManager.ts
[Internal link](https://app.asana.com/0/0/1201952151327802/1201953645973223/f)
> feat: remove ext property from files in favor of mimetype

- packages/snjs/lib/application.ts
- packages/snjs/lib/models/app/userPrefs.ts
- packages/snjs/lib/services/Items/ClientInterface.ts
- packages/snjs/lib/services/Items/ItemManager.spec.ts
- packages/snjs/lib/services/Items/ItemManager.ts
- packages/snjs/lib/ui/note_view_controller.ts
- packages/snjs/mocha/model_tests/notes_tags_folders.test.js
[Internal link](https://app.asana.com/0/1201653402817568/1201978409281331/f)
> feat: option to toggle adding note to all parent folders

- packages/common/src/Domain/Role/RoleName.ts
- packages/responses/src/Domain/Auth/SessionBody.ts
- packages/snjs/lib/services/Api/Session.ts
Add read-only access to sessions
[Internal link](https://app.asana.com/0/1160985268757888/1201942185111145/f)
> Readonly sessions

- packages/snjs/lib/types.ts
Add missing icon types
[Internal link](https://app.asana.com/0/1199942776723820/1201854570633690)
> feat: add file type

- packages/snjs/lib/application_group.ts
[Internal link](https://app.asana.com/0/1201611182420182/1201919410778739/f)
> feat: use workspace terminology for switcher

- packages/filepicker/src/Streaming/StreamingReader.ts
[Internal link](https://app.asana.com/0/1199942776723820/1201942428191885/f)
> fix: streaming reader error on abort selection

- packages/snjs/lib/Models/Note/NoteMutator.ts
[Internal link](https://app.asana.com/0/1201653402817568/1202015218540090/f)
> fix: spellcheck toggle

- packages/snjs/lib/Client/NoteGroupController.ts
- packages/snjs/lib/Client/NoteViewController.ts
[Internal link](https://app.asana.com/0/1201653402817568/1202048773405457/f)
> fix: add parent tags setting when creating note in child tag

- packages/models/src/Domain/Syncable/File/File.ts
- packages/snjs/lib/Services/Items/ItemManager.ts
- packages/snjs/lib/Services/Items/ItemsClientInterface.ts
> feat: make files sortable using setDisplayOptions

- packages/features/src/Domain/Feature/FeatureIdentifier.ts
- packages/features/src/Domain/Feature/Features.ts
[Internal link](https://app.asana.com/0/1201611182420182/1202198361692985/f)
> feat: take Markdown Visual out of beta

- packages/files/src/Domain/FileService.ts
- packages/files/src/Domain/FilesClientInterface.ts
[Internal link](https://app.asana.com/0/0/1202187771437530/1202212618913390/f)
> fix: expose download progress

- packages/models/src/Domain/Syncable/UserPrefs/PrefKey.ts
New mobile-specific pref keys
[Internal link](https://app.asana.com/0/1200588672119490/1202209457862379)
> feat: new mobile-specific pref keys

- packages/snjs/lib/Services/Features/FeaturesService.spec.ts
> fix: role name in FeaturesService unit tests

- packages/snjs/lib/Application/Application.ts
- packages/snjs/lib/Services/Protection/ClientInterface.ts
- packages/snjs/lib/Services/Protection/ProtectionService.spec.ts
- packages/snjs/lib/Services/Protection/ProtectionService.ts
Required for [standardnotes/web@`7e40ed7` (#1035)](https://github.com/standardnotes/web/pull/1035/commits/7e40ed7ad44be46cad6d52fa916a2797e9e076cb)
> feat: generic protected access authorization

- packages/snjs/lib/Application/Application.ts
[Internal link](https://app.asana.com/0/1202173912993191/1202412897951248/f)
> refactor: unify same code for branches

- packages/features/src/Domain/Feature/FeatureIdentifier.ts
> fix: get ExperimentalFeatures identifiers from experimentalFeatures()

- packages/api/package.json
- packages/api/src/Domain/Http/ErrorTag.ts
- packages/api/src/Domain/Http/HttpService.spec.ts
- packages/api/src/Domain/Http/HttpService.ts
- packages/api/src/Domain/Http/HttpServiceInterface.ts
- packages/api/src/Domain/Http/HttpStatusCode.ts
- packages/api/src/Domain/Http/HttpVerb.ts
- packages/api/src/Domain/Http/XMLHttpRequestState.ts
- packages/api/src/Domain/Request/ApiEndpointParam.ts
- packages/api/src/Domain/Request/User/UserRegistrationRequestParams.ts
- packages/api/src/Domain/Server/User/UserServer.spec.ts
- packages/api/src/Domain/Server/User/UserServer.ts
- packages/api/src/Domain/Server/User/UserServerInterface.ts
- packages/snjs/lib/Application/Application.ts
Fixes changes introduced in https://github.com/standardnotes/snjs/pull/771 and addresses issue https://github.com/standardnotes/standalone/issues/72
https://github.com/standardnotes/standalone/issues/72
> fix: setting custom host
