standardnotes/snjs

lib/application.ts, lib/services/protocol_service.ts
Tightening up the changePassword API from the protocol service by not returning the previous root key but only the current server password, which is the only thing that's actually needed by clients.
This password is now also derived from the identical but computed root key instead of the stored root key because the latter is not always guaranteed to have the serverPassword stored in the way that our current SNRootKey class expects. This would make launching the app from a pure 003 installation and performing a protocol upgrade fail.
=> fix: SNProtocolService: return computed server password when changing password

lib/application.ts, lib/services/storage_service.ts
I investigated doing this during the storage upgrade but it would have involved much more work, so instead it works like account-based upgrades.
=> Fix: upgrade with no account and a passcode

dist/@types/application.d.ts, dist/@types/index.d.ts, dist/@types/services/alert_service.d.ts, dist/@types/services/index.d.ts, lib/application.ts, lib/index.ts, lib/services/actions_service.ts, lib/services/alert_service.ts, lib/services/api/messages.ts, lib/services/api/session_manager.ts, lib/services/component_manager.ts, lib/services/index.ts, lib/services/model_manager.ts, lib/services/sync/sync_service.ts, test/application.test.js, test/lib/factory.js, test/upgrading.test.js
- Makes SNAlertService a type which clients have to pass an implementation of in the constructor
- Adds `blockingDialog` method to SNAlertService
- Lets clients clearly know if the protocol upgrade succeeded, failed, or canceled.
- Shows a blocking dialog during the encryption upgrade process (likely needs a better message)
=> Better protocol upgrade api + blocking dialog

lib/services/component_manager.ts
The component manager's `deregisterComponent` method calls sync. Because sync is a very high-level operation with a lot of side-effects it can conflict when we're trying to do something after calling deregisterComponent. In this case, uninstalling it, which will be invalidated by the syncing request completing and determining that the just-disabled component should be kept.
I also think that in general calling sync inside a method named like this is surprising behavior. At least I expected it to do much less work when looking at it.
=> fix: uninstall active extensions

lib/services/component_manager.ts
Aligns `activateComponent`'s behavior with `deactivateComponent`'s and calls sync at a higher level (as it turns out, most of the callers of this method ended up triggering a sync soon after)
=> fix: extract sync out of activateComponent

lib/application.ts, lib/services/sync/sync_service.ts
The SyncService already makes sure that the first online sync is always a DownloadFirstSync. This means that even if this sync fails when we're signing in or registering things will get back in order once the next successful sync occurs.
This PR makes it so that if this initial sync request fails, we try again after a short delay, up to five times.
=> try more than once when running downloadFirstSync

lib/models/core/predicate.ts, test/predicate.test.js
A not operator would allow you to build more powerful filters, which would be especially useful when dealing with an imported a tag hierarchy from another system that you're trying to clean up.
This was [discussed here](https://github.com/standardnotes/forum/issues/262#issuecomment-490623566). But rather than introducing a special syntax to parse, this just treats it as a top-level operator like and/or.
I couldn't find [the docs](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes-and-create-other-dynamic-filters) to update on Github. That should be done if this PR is accepted too.
=> feature: add support for a "not" operator

.github/workflows/tsc.yml
Somehow running `npm run tsc` fails on the default branch. This motivated me to create a Github Action check so it's impossible to miss it next time when someone creates a PR. It runs `npm run tsc` on every push.
=> feature: github action to check tsc on push

dist/@types/models/core/item.d.ts, dist/@types/models/core/predicate.d.ts, dist/@types/services/sync/sync_service.d.ts, lib/models/core/predicate.ts, test/predicate.test.js
This relands b21865baf6c54e46b67d1e80c6fef1bf2abb5385, which was
reverted by commit 316b1b0caa00bb2ad5dde07b3a473c1dba2a65c7.
=> Reland "feature: add support for a "not" operator" with the right types

dist/@types/services/component_manager.d.ts, lib/services/component_manager.ts
This enables classes that extend Component Manager to use alert service. Useful for `presentPermissionsDialog`.
=> feature: make alertService protected in Component Manager

dist/@types/services/sync/sync_service.d.ts, lib/models/core/item.ts
As reported by @johnny243 to me in private, two tests are currently failing because they expect imported data with identical UUIDs but differing contents to be duplicated. This PR fixes that.
=> Fix duplication strategy for imports

dist/@types/services/storage_service.d.ts, dist/snjs.js, lib/services/storage_service.ts
Fixes: StorageService.clearAllData doesn't actually clear all data and can be invalidated by subsequent calls to removeValue.
=> Actually clear all data

test/upgrading.test.js
The _protocol version should be upgraded on password change_ was creating two notes when it was actually assuming only one note was there, which made the test fail half the time.
=> fix: only create one note during password change upgrade test

dist/snjs.js, lib/services/component_manager.ts
Without this change, mobile-only active themes would not be passed to components. Is this enough?
=> fix: use mobile active themes in ComponentManager

dist/@types/services/item_manager.d.ts, dist/@types/services/model_manager.d.ts, dist/snjs.js, lib/services/model_manager.ts, lib/services/sync/sync_service.ts, test/model_tests/importing.test.js
When importing items with UUIDs that conflict with the server, after alternating the UUID the original item was being discarded from PayloadManager but not from storage, causing the app to try to resync that item upon restarting.
With this change, PayloadManager.emitPayloads now returns all the items that it altered instead of letting the sync service query for them, leading to a more predictable and correct result.
=> Remove storage leftovers after import

lib/application.ts, lib/services/alert_service.ts, lib/services/api/messages.ts, lib/services/protocol_service.ts
Passcode operations can take some time. This change warns the user not to close the app during these destructive operations.
=> display blocking dialog during passcode operations

dist/@types/application.d.ts, dist/snjs.js, lib/application.ts
We can avoid reading user for safety reasons and this method becomes synchronous as well.
=> refactor: simplify isEncryptionAvailable in application

dist/snjs.js, lib/services/component_manager.ts
It doesn't make sense to track an editor's `active/inactive` state but before this change it was still happening and could cause bugs when dealing with existing data.
@radko93 If you're using activate/deactivateComponent with editors I don't think it would cause an issue but you can't rely on their active/inactive state and should instead use ComponentManager.editorForNote(SNNote) to determine if an editor should be displayed
=> fix: do not activate or deactivate editors

dist/snjs.js, lib/services/history/session/item_session_history.ts, test/history.test.js
=> fix: session history tests

dist/@types/device_interface.d.ts, dist/@types/services/storage_service.d.ts, dist/@types/services/sync/sync_service.d.ts, lib/device_interface.ts
Because we've used `any` it was possible to return the wrong data format in `getAllRawStorageKeyValues`. This the type which web device interface actually returns and the one that is used in migrations.
=> fix: enforce correct type for getAllRawStorageKeyValues

dist/@types/services/protocol_service.d.ts, dist/snjs.js, lib/application.ts, lib/services/protocol_service.ts, test/keys.test.js, test/upgrading.test.js
I'm not sure how my 003 account got into a state where it had a single itemsKey, but isDefault was not set to true. So upon sign in to the account, when the application attempted to persist data locally, it searched for any key where isDefault is true, and that key was an ephemeral 004 key that the application created on launch.
This ephemeral items key still existed because the full sync had not completed yet, otherwise, it would have been deleted at that point. But because we persist to storage incrementally, it was still a valid key available to SNJS.
It seems like we should be able to perform [this](https://github.com/standardnotes/snjs/blob/004/lib/services/protocol_service.ts#L1230) step on incremental sync as well, not just full syncs. The reason I'm applying this as a mostly …
=> fix: handle case where user may have 003 key not set as default

dist/@types/protocol/versions.d.ts, dist/@types/services/api/messages.d.ts, dist/snjs.js, lib/application.ts, lib/protocol/versions.ts, lib/services/api/messages.ts, lib/services/protocol_service.ts, test/model_tests/importing.test.js
We already prevent importing a backup from an unsupported protocol version, but we also need to prevent importing backups from known version into older accounts.
=> fix: prevent importing new backup file into old account

dist/@types/utils.d.ts, dist/snjs.js, lib/services/protocol_service.ts
Seems like right now the bottleneck of decrypt performance might be "The Bridge" in React Native. I wanted to try to decrypt items concurrently and it improved performance by a significant amount (30% up to 50% using my test data). Problem with React Native bridge is that there is turnaround time, so waiting for every promise to return might not be the best option. I haven't tested all error scenarios yet with this.
=> refactor: decrypt payloads concurrently

dist/@types/application.d.ts, dist/@types/events.d.ts, dist/@types/services/migration_service.d.ts, dist/snjs.js, lib/application.ts, lib/events.ts, lib/services/migration_service.ts
This PR enables the client to check if there are any migrations pending before starting them. This is only possible after `MigrationsLoaded` has happened.
=> feature: hasPendingMigrations

dist/@types/application.d.ts, dist/@types/protocol/payloads/functions.d.ts, dist/@types/services/item_manager.d.ts, dist/snjs.js, lib/application.ts, lib/protocol/payloads/functions.ts, lib/services/item_manager.ts, test/item_manager.test.js
Expose ItemManager.duplicateItems to clients and let them specify content overrides (useful for restoring item revisions as copies or duplicating notes in the future)
Also adds test to ensure a duplicated note keeps its editors and tags.
=> feat: duplicate item content overrides

lib/protocol/payloads/pure_payload.ts
When we have errors reported there we don't know what types of items fail. This will make it easier to debug errors.
=> fix: update missing uuid error with content type

dist/@types/application.d.ts, dist/@types/protocol/root_key.d.ts, dist/@types/services/api/api_service.d.ts, dist/@types/services/api/messages.d.ts, dist/@types/services/api/responses.d.ts, dist/@types/services/api/session_manager.d.ts, dist/@types/services/challenge/challenge_service.d.ts, dist/@types/services/key_recovery_service.d.ts, dist/@types/services/protocol_service.d.ts, dist/snjs.js, lib/application.ts, lib/protocol/root_key.ts, lib/services/api/api_service.ts, lib/services/api/messages.ts, lib/services/api/responses.ts, lib/services/api/session_manager.ts, lib/services/challenge/challenge_service.ts, lib/services/key_recovery_service.ts, lib/services/protocol_service.ts, test/key_recovery_service.test.js, test/keys.test.js, test/lib/factory.js, test/session.test.js, test/upgrading.test.js
- Fixes issue where setting the root key on sign in/register would also call encryptAllItemsKeys (should only be called on password change)
- Fixes issue where performing a sign in through detached session recovery wouldn't set global root key. This is fixed via the fact that the main sign in function (through the auth completion handler) now sets the root key directly, as opposed to letting callers be responsible for this.
=> refactor: main auth completion handler should be responsible for setting root key

dist/snjs.js, lib/services/item_manager.ts
When resetting local data (Like before signing in without merging with local data) uninitialized theme display options would cause errors
=> fix: initialize theme display options

dist/@types/storage_keys.d.ts, dist/snjs.js, lib/migrations/2020-01-15.ts, lib/storage_keys.ts, test/migrations/2020-01-15-mobile.test.js
This PR resolves following issues:
- passcode keybord type is migrated
- server is migrated from user to default snjs location
- `hideTags` is back (and migrated)
=> fix: mobile migrations improvments

dist/@types/services/api/api_service.d.ts, dist/@types/services/api/responses.d.ts, dist/snjs.js, lib/services/api/api_service.ts, lib/services/api/http_service.ts, lib/services/api/responses.ts, lib/services/api/session_manager.ts
Also renamed `HttpStatusCode` to `StatusCode` as there was already a precedent set for using proprietary code numbers
=> fix: do not attempt to sign in again when canceling MFA prompt

dist/snjs.js, lib/migrations/2020-01-15.ts, test/migrations/2020-01-15-mobile.test.js
Passcode keyboard type was not stringified so it has to be read directly.
=> fix: mobile passcode keyboard type migration

dist/@types/device_interface.d.ts, lib/device_interface.ts, lib/migrations/2020-01-15.ts
Unfortunately, it's not possible to use generic methods when extending abstract classes in typescript so this has to be refactored.
=> fix: remove generic types from abstract class

dist/@types/index.d.ts, dist/@types/log.d.ts, dist/snjs.js, lib/application.ts, lib/index.ts, lib/log.ts, lib/protocol/operator/002/operator_002.ts
At first I wanted to throw or return errors from operators but it would have been an extremely disruptive change and have broken all the tests, so I went with a singleton where clients can set its error reporter like this:
```ts
SNErrors.onUnhandledError = (error) => {
// Report error, e.g with Bugsnag
}
```
And SNJS can call like this, anywhere in the app:
```ts
SNErrors.onUnhandledError(Error('...'));
```
=> feature: add error reporting singleton

.dockerignore, .github/workflows/pr.yml, .github/workflows/publish.yml, Dockerfile, README.md, docker-compose.yml, package-lock.json, package.json, test.sh, test/lib/factory.js, test/test.html
- Added running a Docker orchestrated test suite
- Added the test suite to run on github workflows
You can run the test suite locally without having to open the browser by typing `npm test`.
You can also see the tests that have been run on this PR
*NOTE*: Please keep in mind that the tests on this PR should be failing as this is the current state of the tests. This PR only introduces the setup for running tests and should be merged even though a failing check status. The tests that are failing should be fixed in a separate issue/PR.
=> feat: add running test suite orchestrated with Docker

lib/services/component_manager.ts, package-lock.json, package.json
There are some random cases when `component.window` is undefined and accessing `postMessage` fails (even if there is a check up there). This can happen when app gets locked suddently or when the users leaves the screen before an event is sent from the editor.
=> fix: safe use of postMessage

docker-compose.yml, package.json, test/proxy.conf.template
This reroutes all the session management traffic (in the js test suite) to syncing-server-js.
The following paths/resources are rerouted:
```
post "session/refresh" => "api/sessions#refresh"
get "sessions" => "api/sessions#index"
delete "session" => "api/sessions#delete"
delete "session/all" => "api/sessions#delete_all"
```
=> feat: reroute sessions to syncing-server-js

lib/application.ts, lib/index.ts, lib/services/api/api_service.ts, lib/services/api/http_service.ts, lib/services/api/responses.ts, lib/services/api/session.ts, lib/services/api/session_manager.ts, package.json, test/session.test.js
Adds `SNApplication.getSessions()` and `SNApplication.revokeSession(uuid)`, filling in the missing functionality in apiService and sessionManager (mostly DELETE requests)
=> client-facing sessions management

lib/index.ts, lib/platforms.ts, package.json
- adds a new function `environmentFromString`
- fixes type `(map as any)` on `platformFromString`
At the moment, `environmentFromString` will be used [here](https://github.com/johnny243/sn-components-api/blob/68b9dd1e5ea89ae99bb022a6f828da3883a6a87b/test/manager.test.ts#L140).
Also, `environmentFromString` is added to complement `environmentToString`.
=> feat: environmentFromString function

package.json
As the minimum node version supported natively in arm64 Macs is 15, it would be good if we could add support for it.
=> chore: add support for node 15

README.md
The specification link is currently broken. I updated the link with a relative link to the correct file. A relative link is better than an absolute link since it works across branches.
=> chore: update README.md with correct link to encryption specification

packages/config/package.json, packages/config/src/.eslintrc, packages/domain-events/package.json, packages/domain-events/src/Infra/SQS/SQSDomainEventSubscriberFactory.ts
This enforces a 2-space indentation style for all projects using `@standardnotes/config` in versions `1.1.1+`
=> fix: enforce 2 spaces indentation

packages/snjs/lib/index.ts, packages/snjs/lib/utils.ts, test/utils.test.js
Add isSameDay util that returns a boolean indicating whether two dates correspond to the same day. This util is moved here because it's used both for web and mobile.
=> feat: add isSameDay util

packages/snjs/lib/models/app/userPrefs.ts, packages/snjs/lib/services/preferences_service.ts, packages/snjs/lib/services/pure_service.ts, packages/snjs/lib/services/singleton_manager.ts, packages/snjs/package.json, test/preferences.test.js, test/singletons.test.js
Currently preferences are only loaded after a full sync event has completed, which is much later than when a user can interact with their notes
=> fix: eagerly load preferences

packages/snjs/lib/application.ts, packages/snjs/lib/challenges.ts, packages/snjs/lib/services/api/messages.ts, packages/snjs/lib/services/protection_service.ts, packages/snjs/package.json, test/backups.test.js
Add authorizedEncrypted parameter to createBackupFile method that defaults to false. When set to true, creating an encrypted backup will be a protected action.
=> Add protected encrypted backups

packages/config/package.json, packages/config/src/.eslintrc, packages/config/src/.prettierrc
As discussed with @mobitar and @karolsojko, added rules for ignoring vars (`_name`) and to require curly braces around if/else at all times.
=> feat: add linter rules: varsIgnorePattern, curly/all

packages/snjs/lib/index.ts, packages/snjs/lib/protocol/payloads/deltas/conflict.ts, packages/snjs/lib/services/item_manager.ts, packages/snjs/lib/services/payload_manager.ts, packages/snjs/lib/services/sync/account/operation.ts, packages/snjs/lib/services/sync/sync_service.ts, test/auth-fringe-cases.test.js, test/sync_tests/conflicting.test.js, test/sync_tests/online.test.js
If 151 items are set to sync, and the per page limit is 150, then the 151st item will be queued to sync after the first page completes. We want to make sure that in the second sync, the latest value of the 151st item is used, and not its value when it was first marked as dirty
Previously, if all 151 items were marked as dirty together, then the value of the 151st item would be frozen in time of setting to dirty, and after the first page request, a second page sync request is made using that potentially stale value. In this solution, we always read the present value of an item right before sending it to the server. So we are instead holding in memory the UUIDs of dirty items, rather than a static frozen-in-time representation of the values it had when it was dirtied.
=> Present-value sync

packages/snjs/lib/application.ts, packages/snjs/lib/challenges.ts, packages/snjs/lib/services/api/messages.ts, packages/snjs/lib/services/protection_service.ts, packages/snjs/package.json, test/protection.test.js
- Extracted some methods needed for multiple selection logic: getAuthorizedNotesForProtectedAction (not sure about the right naming) so that we only prompt for authentication challenge once and authorize a protected action on a batch of notes, and protectNotes and unprotectNotes to protect/unprotect in batch.
- Added SelectProtectedNote challenge reason and its corresponding text.
=> feat: add methods for multiple selection

packages/snjs/lib/index.ts, packages/snjs/lib/models/app/component.ts, packages/snjs/lib/services/component_manager.ts, packages/snjs/lib/services/index.ts, packages/snjs/package.json
For https://github.com/standardnotes/component-relay/pull/34
=> feat: KeyPressed component action

packages/snjs/lib/application.ts, packages/snjs/lib/services/item_manager.ts, packages/snjs/package.json, test/item_manager.test.js
- Use regex for query matching, so that a result will be returned if either the title starts with the query, or the query is present after a delimiter. This means if we have a tag with a "parent.child.grandchild" title, searching for "parent.child" and "child.grandchild" will both return it as a result.
- Add optional note parameter to searchTags method, so that when this parameter is passed, tags associated with that note will not be returned in results. This will allow us to show only tags not currently added to the note in the search dropdown.
=> feat: use regex and add note parameter for searchTags

packages/snjs/lib/application.ts, packages/snjs/lib/index.ts, packages/snjs/lib/protocol/collection/item_collection.ts, packages/snjs/lib/services/item_manager.ts, packages/snjs/lib/utils.ts, packages/snjs/package.json, test/item_manager.test.js, test/utils.test.js
- Added naturalSort util which uses Intl.Collator (if available), and if not, locale.compare.
- Modified searchTags to use naturalSort util, to use the case-insensitive flag in the regex instead of transforming strings using toLowerCase(), and to compare tag UUID instead of the entire tag when filtering out tags already in a note.
- Added getSortedTagsForNote method, which returns tags for a note in natural order. This will be used to display tags in the current note, now that we will no longer show them joined in a string.
- Added { numeric: true } parameter to item sorting by title, so notes ordered by title are sorted in natural order
=> feat: natural sort tags and notes

packages/snjs/lib/protocol/payloads/pure_payload.ts, packages/snjs/lib/services/history/entries/history_entry.ts, packages/snjs/lib/services/history/entries/note_history_entry.ts, packages/snjs/package.json, test/history.test.js
See https://github.com/standardnotes/mobile/issues/432
=> fix: use created_at for unsynced session history entries

docker-compose.yml, packages/snjs/lib/application.ts, packages/snjs/lib/services/api/api_service.ts, packages/snjs/lib/storage_keys.ts, packages/snjs/package.json, test/lib/factory.js, test/test.html
- added the `alternativeHost` property so that we can switch endpoints one by one to an upgraded version of the API. Will come in handy when switching to for example `v2` as well in future. The naming could be better than `alternativeHost` I guess so I'm open for propositions.
- switched the sign out action to utilize API `v1` instead of `v0`.
=> feat: add alternative host and switch sign out to API v1

packages/snjs/lib/application.ts, packages/snjs/lib/services/item_manager.ts, packages/snjs/package.json, test/item_manager.test.js
Added getTagDescendants method, which will allow us to remove any descendant tags when a user removes a parent tag from a note.
=> feat: add getTagDescendants

packages/snjs/lib/application.ts, packages/snjs/package.json
Make webSocketUrl optional on SNApplication, so clients won't connect to the WebSocket if they don't include this in the constructor.
=> feat: make webSocketUrl optional

packages/domain-events/package.json, packages/domain-events/src/Domain/Event/UserRoleChangedEvent.ts, packages/domain-events/src/Domain/Event/UserRoleChangedEventPayload.ts, packages/domain-events/src/Domain/index.ts
I was thinking about the events structure that we are going to utilize in the websockets communication and I think the events that we already use for SNS/SQS are good for using in websockets as well. So it's enough if we publish a `USER_ROLE_CHANGED` event via websockets and the client will know to re-fresh features based on that. @antsgar wdyt?
=> feat: add user role changed event for websockets purposes

packages/features/package.json, packages/features/src/Domain/Feature/features.json
- Adds note types
- Adds file extension for when exporting a note
- Adds `interchangeable`, which determines whether a note can be opened with any editor of the same note type. For example all markdown editors are interchangeable, but notes using authentication editors like TokenVault cannot be opened with any other editor.
=> feat: editor note and file types

packages/snjs/package.json
Bump `@standardnotes/features` version to 1.7.1 to possibly fix errors mentioned here: https://github.com/standardnotes/web/pull/688#discussion_r731125408
=> chore: Bump @standardnotes/features to 1.7.1

package.json
Fix versioning by removing conventional graduates from Lerna command
https://github.com/lerna/lerna/issues/2532
=> fix: remove conventional graduate from lerna versioning

.github/workflows/publish.yml
Remove the tests upon deployment aka master push. I've made the lint, unit test and e2e test status checks required on all PRs and also added the requirement that a PR has to be in sync with the latest master so now it's redundant to run those once again whenever a PR is merged to master. This would cut the time-to-publish time in half.
N/A
=> fix: remove running tests upon deployment - ensured on PR status checks

packages/domain-events/src/Domain/Event/SubscriptionSyncRequestedEventPayload.ts
Add `canceled` property missing from sync payload.
https://app.asana.com/0/1200980603427038/1201573386680719/f
=> fix: add missing canceled property from subscription sync requested event

packages/snjs/lib/models/app/userPrefs.ts
Replaces 'None' with 'Default' for the typedef of Auto[..]ThemeIdentifier userPref
=> refactor: Replace 'None' with 'Default' for AutoThemeIdentifier

packages/snjs/lib/services/component_manager.spec.ts, packages/snjs/lib/services/component_manager.ts
Adds a `doesEditorChangeRequireAlert(from, to)` function to see if switching between editors requires an alert and a `showEditorChangeAlert()` function to show that alert.
=> feat: add function to check if editor change requires alert

docker-compose.canary.yml, docker-compose.yml
This image of ElasticMq should support both amd64 and arm64 architecture.
[Internal link](https://app.asana.com/0/1201389347530783/1201748156300213/f)
=> fix: sqs image to support arm64 and amd64 architecture

packages/snjs/lib/models/app/note.spec.ts, packages/snjs/lib/models/app/note.ts
Hi there! :hugs:  
This implementation prevents unknown types from breaking note's state when creating from PayloadContent and the PR describes how to reproduce the problem.
This implementation prevents notes with unexpected types on a string to leave the app in an unusable state. Even though the problem was detected with `Note.preview_plain: string` it could happen on any field being constructed from PayloadContent since all properties are explicitly typed `any`.  
:warning: I am unsure of typing _Boolean_ since it could cause unexpected behaviour (`Boolean("false") → true`) but I found no test or implementation that would be threatened by it.
Last week I reported to @moughxyz an issue when logging into my account where my notes would not be loaded and were completely unaccessible …
=> fix(note): prevents unknown types from breaking note's state when creating from PayloadContent

packages/domain-events/src/Domain/Event/UserSignedInEventPayload.ts
Sets `browser` property as optional.
[Internal link](https://app.asana.com/0/1160985268757888/1201916964421230)
=> fix: optional browser property

packages/filepicker/src/classic_reader.ts, packages/filepicker/src/streaming_reader.ts
Adds an optional `file` or `fileHandle` param to `selectFile()`
=> feat: allow passing file or filehandle to reader as param

packages/responses/src/Domain/Auth/KeyParamsData.ts
Add missing legacy email field for KeyParams response from the server which is present in protocols 002 and 001
N/A
=> fix: add missing legacy email field on key params data

packages/filepicker/src/utils.spec.ts, packages/filepicker/src/utils.ts
Adds GB support to `formatSizeAsReadableString` function, and adds a test for it. Required for displaying files quota correctly.
=> feat: add GB support to formatSizeAsReadableString

docker-compose.yml, packages/snjs/mocha/session.test.js
Allow expired token request for session sign out
[Internal Link](https://app.asana.com/0/1160985268757888/1202162717384437/f)
=> fix: update auth to allow expired token session sign outs

packages/filepicker/src/utils.spec.ts, packages/filepicker/src/utils.ts
Fix file size calculation to binary - currently 107374182400 bytes doesn't show up as 100GB but 107.37 GB
N/A
=> fix: file size calculation to binary

packages/snjs/lib/Services/Api/ApiService.ts, packages/snjs/lib/Services/Api/HttpService.ts
Fixes issue where downloading external extensions from places like https://cdn.jsdelivr.net/gh/dracula/standard-notes@master/sn-theme-dracula.json would fail due to destination rejecting custom headers.
=> fix: do not send custom headers for external request

packages/snjs/lib/Client/IconsController.ts
- gets the `icon` and `tint color` from the editor's `note_type` field instead of the editor's identifier.
[Internal link](https://app.asana.com/0/1201653402817568/1202267692424063/f)
=> fix: get icon and tint from note type

packages/common/src/Domain/Role/RoleName.ts, packages/common/src/Domain/Subscription/SubscriptionName.ts, packages/features/src/Domain/Feature/Features.spec.ts, packages/features/src/Domain/Feature/Lists/ServerFeatures.ts, packages/snjs/lib/Services/Features/FeaturesService.spec.ts, packages/snjs/lib/Services/Features/FeaturesService.ts, packages/snjs/mocha/features.test.js
Remove Basic user role and subscription core plan as they are no longer used.
[Internal link](https://app.asana.com/0/1160985268757888/1202254390984714/f)
=> feat: remove basic user role and core subscription plan
